title: Products
sites:
  - en
  - de
template: products/show
layout: layout
taxonomies:
  - categories
revisions: false
route: '/products/{slug}'
sort_dir: asc
date_behavior:
  past: public
  future: private
